name: Run tox

on:
  push:
    paths-ignore:
      - README.md
      - .pre-commit-config.yaml
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - .pre-commit-config.yaml
      - .gitignore

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pdm install -d -G test -G lint
    - name: Test with tox
      run: pdm run tox
